services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: pentest_container
    ports: 
      - 5000:5000
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: SecOps-Frontend
    ports:
      - 3000:4321