import swaggerJsdoc from "swagger-jsdoc";

// swagger.js
// const swaggerJsdoc = require('swagger-jsdoc');



const options = {
    definition: {
        openapi: '3.0.0',
        info: {
            title: 'My API',
            version: '1.0.0',
            description: 'Express API with autogenerated Swagger doc',
        },
        servers: [
            {
                url: 'http://localhost:5000',
            },
        ],
    },
    apis: ['./routes/*.js'], // files containing annotations for the Swagger doc
};

// const swaggerJsdc = swaggerJsdoc(options);
const swaggerSpec = swaggerJsdoc(options);

// module.exports = swaggerSpec;

export default swaggerSpec