import { Inter } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/layouts/AppLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SOC Playbooks",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // fallback
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-background`}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
